[options]
admin_passwd = 1234
db_host = localhost
db_port = 1234
db_user = odoo
db_password = 1234
addons_path = /Users/ishmamkhan/Desktop/odoo17_E/odoo/addons,/Users/ishmamkhan/Desktop/odoo17_E/odoo/odoo/addons,/Users/ishmamkhan/Desktop/odoo17_E/enterprise-17.0,/Users/ishmamkhan/Desktop/odoo17_E/custom1/BRAC/BRAC-AI-Ishmam
http_port = 8070
default_productivity_apps = True